systems/linux/user/x86-smp_generic_64-2_6/linux-bcm-knet.ko lib/modules/6.2.0-39-generic/extra
systems/linux/user/x86-smp_generic_64-2_6/linux-kernel-bde.ko lib/modules/6.2.0-39-generic/extra
systems/linux/user/x86-smp_generic_64-2_6/linux-user-bde.ko lib/modules/6.2.0-39-generic/extra
systems/linux/user/x86-smp_generic_64-2_6/linux-knet-cb.ko lib/modules/6.2.0-39-generic/extra
systemd/opennsl-modules.service lib/systemd/system
sdklt/linux/bde/linux_ngbde.ko lib/modules/6.2.0-39-generic/extra
